version: '3.4'

services:
  cypressdownloadfile:
    image: cypressdownloadfile
    build:
      context: node_modules/cypress-downloadfile
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3030:3030
